#
#       Created by Harrison Miller
#       Course CS223, Spring 2016
#       Problem Set 3
#
#       Makefile

# Specify compiler
CC=gcc

# Specify flags and other macros
CFLAGS=-std=c99 -g3 -Wall -pedantic
HWK3 = /c/cs223/Hwk3/

boggle: boggle.c
	$(CC) $(CFLAGS) -o boggle boggle.c

clean:
	rm -f boggle
